In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

    age  gender   review education purchased
31   22  Female     Poor    School       Yes
8    65  Female  Average        UG        No
38   45  Female     Good    School        No
45   61    Male     Poor        PG       Yes
28   48    Male     Poor    School        No

In [4]:
df= df.iloc[:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
X_train = df.iloc[:,:-1]
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)
X_train_scaled = oe.transform(X_train)

In [9]:
X_train_scaled= pd.DataFrame(X_train_scaled,columns=X_train.columns)
X_train_scaled.head()

   review  education
0     1.0        0.0
1     0.0        1.0
2     2.0        2.0
3     2.0        2.0
4     1.0        1.0

In [12]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y_train = df.iloc[:,-1]
le.fit(y_train)
y_train_scaled = le.transform(y_train)
y_train_scaled= pd.DataFrame(y_train_scaled,columns=['y'])

In [13]:
y_train_scaled.head()

   y
0  0
1  0
2  0
3  0
4  0

In [14]:
y_train_scaled.sample(5)

    y
44  0
49  0
47  1
29  1
38  0